### PR TITLE
Test dev branch against avs 0.9.1-SNAPSHOT

### PR DESCRIPTION
**Pull request by dwelch-spike**
Had to make some more changes in here to support AVS 0.9.1 so requesting reviews to merge.

### CODE REVIEW

**Comment by dwelch-spike** [comment]
Looks like not all the necessary changes were made for VEC-256 and VEC-241.
Had to...
- regenerate proto code
- add apply_defaults in a few places
- fix incorrect indexParallel and reIndexParallel proto field usage

**Review by DomPeliniAerospike — APPROVED** [review]
Changes look great, and 0.9.1 is tested and passing testing.

LGTM

**Review by DomPeliniAerospike — CHANGES_REQUESTED** [review]
Took a quick second look, not sure if apply_defaults is correctly tested.

**Comment by dwelch-spike** [comment]
I'll add a apply_defaults test in another PR

**Pull request merged**
