### PR TITLE
feat: add index_get_percent_unmerged client method vec-382

### PR DESCRIPTION
**Pull request by dwelch-spike**

### CODE REVIEW

**Comment by dwelch-spike** [comment]
TODO async implementation and decide if we need to wait for unmerged records to be initialized.

**Comment by dwelch-spike** [comment]
> TODO async implementation and decide if we need to wait for unmerged records to be initialized.

Did async implementation, not waiting for unmerged records stat to be non 0.

**Comment by dwelch-spike** [comment]
A few notes about this PR.

1. It is difficult to test the percent unmerged with any exact values because it is based on the timing of index record merging and healer runs, and stats collection server side. Hence the tests only verify that things are above an expected threshold.
2. I added some test fixtures for record and index setup and teardown that I will use in the rest of the test suite in another PR.

**Review by DomPeliniAerospike — APPROVED** [review]
LGTM! 

Love the improvement on the `wait_for_index_completion`. Docs describe the behavior well!

**Pull request merged**
