### PR TITLE
fix: Set max_mem_queue_size field in fromIndexDefinition, test: add apply_defaults tests, chore: update repr and str methods in types.py with new HNSWParam fields. Finishing touches for vec-275 and vec-241.

### PR DESCRIPTION
**Pull request by dwelch-spike**
This PR ballooned in scope, I'll split the formatting out next time. I noticed and added a few things.
- max_mem_queue_size was missing in fromIndexDefinition, added it
- the __str__ and __repr__ methods on the HNSWParams and nested types were missing or missing some fields which made debugging more difficult, I added them, let me know what you think. Printing IndexDefinition now looks like this, which is a little wonky, I added a todo to clean it up.
```
IndexDefinition(id=IndexId(namespace=test, name=l), dimensions=1024, field=science, sets='', vector_distance_metric=0, hnsw_params=hnswParams {
  m: 16
  efConstruction: 100
  ef: 100
  batchingParams {
  maxRecords: 100000
  interval: 30000
}
  maxMemQueueSize: 1000000
  HnswCachingParams {
  max_entries: 2000000
  expiry: 3600000
}
  HnswHealerParams {
  max_scan_rate_per_node: 1000
  max_scan_page_size: 10000
  re_index_percent: 10.0
  schedule: 0 0/15 * ? * * *
  parallelism: 1
}
  HnswIndexMergeParams {
  index_parallelism: 80
  reindex_parallelism: 26
}
}, storage=IndexStorage {
  namespace: test
  set_name: l
}, index_labels={}
```
__repr__ looks like...
```
IndexDefinition(id=IndexId(namespace='test', name='1OTDhIQo37_8zkcI8VDMi-x9Gl6Ph0'), dimensions=1024, field='science', sets='',vector_distance_metric=0, hnsw_params=HnswParams(m=16, ef_construction=100, ef=100, batchingParams(max_records=100000, interval=30000), max_mem_queue_size=1000000, cachingParams(max_entries=2000000, expiry=3600000), healerParams(max_scan_rate_per_node=1000, max_scan_page_size=10000, re_index_percent=10.0, schedule=0 0/15 * ? * * *, parallelism=1), indexMergeParams(index_parallelism=80, reindex_parallelism=26)), storage=IndexStorage(namespace='test', set_name='1OTDhIQo37_8zkcI8VDMi-x9Gl6Ph0'), index_labels={}
```
- added apply_defaults tests
- formatted everything with black
- bumped dev version to 3

### CODE REVIEW

**Comment by dwelch-spike** [comment]
Non formatting changes are in...
admin_helpers.py
conversions.py
types.py
tests for index_get and index_list

**Review by DomPeliniAerospike — APPROVED** [review]
LGTM!

**Comment by DomPeliniAerospike** [comment]
Note: We should only format before a release or get pre-commit hooks which automatically runs black before commits.

Checking every formatting change is not necessary, and makes it more likely to miss actual mistakes.

Until pre-commit hooks are implemented, lets just plan on formatting and committing directly to stage, since these changes shouldn't affect any code.

**Comment by dwelch-spike** [comment]
> Note: We should only format before a release or get pre-commit hooks which automatically runs black before commits.
> 
> Checking every formatting change is not necessary, and makes it more likely to miss actual mistakes.
> 
> Until pre-commit hooks are implemented, lets just plan on formatting and committing directly to stage, since these changes shouldn't affect any code.

So format the dev branch before release? Sounds good to me.

**Pull request merged**
